
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Command\:
    resource: '%kernel.project_dir%/app/Command/'

  App\Command\DocsPrerenderCommand:
    arguments:
      - '@Local\ContentRenderer\Renderer\DocumentationRenderer'

  App\Command\DocsUpdateCommand:
    arguments:
      $temp: '%kernel.cache_dir%'
      $public: '%kernel.project_dir%/public'
      $renderer: '@Local\ContentRenderer\Renderer\DocumentationRenderer'
