
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # ----------------------------------------------------------------------------
  #  Repositories
  # ----------------------------------------------------------------------------

  App\Infrastructure\Persistence\Repository\Documentation\CategoryRepositoryInterface:
    class: App\Infrastructure\Persistence\Repository\Documentation\DatabaseCategoryRepository

  App\Infrastructure\Persistence\Repository\Documentation\PageRepositoryInterface:
    class: App\Infrastructure\Persistence\Repository\Documentation\DatabasePageRepository

  # ----------------------------------------------------------------------------
  #  Listeners
  # ----------------------------------------------------------------------------

  App\Infrastructure\Persistence\Doctrine\Listener\CreatedAtListener:
    tags:
      - { name: doctrine.event_listener, event: prePersist }

  App\Infrastructure\Persistence\Doctrine\Listener\UpdatedAtListener:
    tags:
      - { name: doctrine.event_listener, event: preUpdate }

  # ----------------------------------------------------------------------------
  #  Subscribers
  # ----------------------------------------------------------------------------

  App\Infrastructure\Persistence\Doctrine\Subscriber\UrlGeneratorSubscriber:
    arguments:
      $slugger: '@App\Infrastructure\Slugger\CaseInsensitiveSlugger'
    tags:
      - { name: doctrine.event_subscriber }

  App\Infrastructure\Persistence\Doctrine\Subscriber\ContentRenderSubscriber:
    arguments:
      - '@Local\ContentRenderer\Renderer\DocumentationRenderer'
    tags:
      - { name: doctrine.event_subscriber }

