parameters:
  github_hook_secret: '%env(resolve:GITHUB_HOOK_SECRET)%'

imports:
  - { resource: services/*.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # ----------------------------------------------------------------------------
  #  Controllers
  # ----------------------------------------------------------------------------

  App\Controller\:
    resource: '../app/Controller'
    public: true

  App\Controller\SystemController:
    arguments:
      - '%github_hook_secret%'

  # ----------------------------------------------------------------------------
  #  Symfony PSR-20 Clock
  # ----------------------------------------------------------------------------

  Symfony\Component\Clock\NativeClock: ~

  Symfony\Component\Clock\ClockInterface:
    alias: Symfony\Component\Clock\NativeClock

  Psr\Clock\ClockInterface:
    alias: Symfony\Component\Clock\NativeClock

  # ----------------------------------------------------------------------------
  #  Symfony Slugger
  # ----------------------------------------------------------------------------

  Symfony\Component\String\Slugger\AsciiSlugger:
    arguments:
      - '%kernel.default_locale%'

  Symfony\Component\String\Slugger\SluggerInterface:
    alias: Symfony\Component\String\Slugger\AsciiSlugger
